spring:
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

  datasource:
    url: jdbc:h2:mem:ide;NON_KEYWORDS=USER;
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true