spring:
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  datasource:
    url: jdbc:mysql://my-ide.callxiy6n1zh.ap-northeast-2.rds.amazonaws.com:3306/ide?characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: admin
    password: ${password}
server:
  error:
    include-message: always
    include-binding-errors: always
  servlet:
    context-path: /ideApi

docker:
  value:
    email : ${email}
    password : ${password}
username: ${username}
